Update workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,14 +1,9 @@
 name: generate animation
 
 on:
-  # run automatically every 12 hours
   schedule:
     - cron: "0 2 * * *"
-
-  # allows to manually run the job at any time
   workflow_dispatch:
-
-  # run on every push on the main branch
   push:
     branches:
       - main
@@ -19,7 +14,9 @@ jobs:
     timeout-minutes: 10
 
     steps:
-      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
       - name: generate github-contribution-grid-snake.svg
         uses: Platane/snk/svg-only@v3
         with:
@@ -27,12 +24,21 @@ jobs:
           outputs: |
             dist/github-contribution-grid-snake.svg
             dist/github-contribution-grid-snake-dark.svg?palette=github-dark
-      # push the content of <build_dir> to a branch
-      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
+
+      - name: Check if files exist
+        run: |
+          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
+            echo "File not found!"
+            exit 1
+          fi
+
+      - name: Log generated files
+        run: ls -R dist
+
       - name: push github-contribution-grid-snake.svg to the output branch
         uses: crazy-max/ghaction-github-pages@v4
         with:
           target_branch: output
           build_dir: dist
         env:
-          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}          
+          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
